name: CBOR Module Tests

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - "cbor/**"
      - ".github/workflows/cbor-unit-tests.yml"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run CBOR module unit tests
        run: ./gradlew :cbor:test

      - name: Generate test reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: test-reports
          path: cbor/build/reports/tests/
