name: Proximity - Unit Tests

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - "proximity/**"
      - ".github/workflows/proximity-unit-tests.yml"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Proximity module unit tests
        run: ./gradlew :proximity:test

      - name: Generate test reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: proximity-test-reports
          path: proximity/build/reports/tests/
