name: Unit Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  filter:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed for actions/checkout

    outputs:
      cbor: ${{ steps.filter.outputs.cbor }}
      proximity: ${{ steps.filter.outputs.proximity }}
    steps:
      - name: Filter CBOR and Proximity paths
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            cbor:
              - 'cbor/**'
            proximity:
              - 'proximity/**'
            workflow:
              - '.github/workflows/unit-tests.yml'

  setup:
    needs: filter
    if: needs.filter.outputs.cbor == 'true' || needs.filter.outputs.proximity == 'true' || needs.filter.outputs.workflow == 'true' || 'true' == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed for actions/checkout

    outputs:
      cbor: ${{ needs.filter.outputs.cbor }}
      proximity: ${{ needs.filter.outputs.proximity }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

  cbor-tests:
    needs: setup
    if: needs.filter.outputs.cbor == 'true' || needs.filter.outputs.workflow == 'true' || 'true' == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed for actions/checkout

    steps:
      - name: Run CBOR module unit tests
        run: ./gradlew :cbor:test

      - name: Report CBOR test results
        uses: dorny/test-reporter@6e6a65b7a0bd2c9197df7d0ae36ac5cee784230c # v2.0.0
        with:
          name: CBOR Tests JUnit Report
          path: cbor/build/test-results/**/*.xml
          reporter: java-junit
          fail-on-error: true
          path-replace-backslashes: true

  proximity-tests:
    needs: setup
    if: needs.filter.outputs.proximity == 'true' || needs.filter.outputs.workflow == 'true' || 'true' == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run Proximity module unit tests
        run: ./gradlew :proximity:test

      - name: Report Proximity test results
        uses: dorny/test-reporter@6e6a65b7a0bd2c9197df7d0ae36ac5cee784230c # v2.0.0
        with:
          name: Proximity Tests JUnit Report
          path: proximity/build/test-results/**/*.xml
          reporter: java-junit
          fail-on-error: true
          path-replace-backslashes: true
